// <auto-generated />
using Managment.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Managment.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Managment.Models.MarksDetail", b =>
                {
                    b.Property<int>("MarksId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MarksObtained")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MarksId");

                    b.ToTable("MarksDetails");

                    b.HasData(
                        new
                        {
                            MarksId = 1,
                            MarksObtained = 90,
                            Subject = "Math"
                        },
                        new
                        {
                            MarksId = 2,
                            MarksObtained = 85,
                            Subject = "Science"
                        },
                        new
                        {
                            MarksId = 3,
                            MarksObtained = 75,
                            Subject = "History"
                        });
                });

            modelBuilder.Entity("Managment.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Section = "Class A",
                            StudentName = "Ram"
                        },
                        new
                        {
                            StudentId = 2,
                            Section = "Class B",
                            StudentName = "Seetha"
                        },
                        new
                        {
                            StudentId = 3,
                            Section = "Class C",
                            StudentName = "John"
                        });
                });

            modelBuilder.Entity("Managment.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            TeacherName = "Ramesh"
                        },
                        new
                        {
                            TeacherId = 2,
                            TeacherName = "Rahul"
                        },
                        new
                        {
                            TeacherId = 3,
                            TeacherName = "Akhil"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
